quarkus.http.port=8080
quarkus.banner.enabled=true

# Optionnel : conserver le fichier temporaire après la réponse
quarkus.http.body.delete-uploaded-files-on-end=false

# Taille max du body HTTP entier (ex: 200 Mo)
quarkus.http.limits.max-body-size=200M

# Taille max d'une part multipart (doit aussi être augmentée)
quarkus.http.limits.max-form-attribute-size=200M

# Taille max des fichiers uploadés
quarkus.http.body.uploads-directory=uploads
quarkus.http.body.handle-file-uploads=true